workflows:
  android-workflow:
    name: Android WebView Build

    environment:
      java: 17

    scripts:
      - chmod +x gradlew
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      scripts:
  - name: Set permissions
    working_directory: android
    script: |
      chmod +x gradlew
      chmod +x android/gradlew
      
      